name: Reusable Deploy
# workflow_call: 他のワークフローからこのワークフローを呼び出すことをトリガーに設定する。
on: workflow_call
jobs:
  Deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Output information
        run: |
          echo "this is reusable.yml"
          echo "Deploying & uploading..."
